name: Despliegue Producción EC2

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: [self-hosted, linux, ec2-deploy]

    steps:
    - name: Actualizar código y Desplegar
      run: |
        cd /home/ubuntu/agenda-cultural
        
        git pull origin main
        
        make deploy-full
